server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/fraudshielddb?TimeZone=Asia/Kolkata
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: alert-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: "com.fraudshield.fraud.dto.FraudAlertEvent:com.fraudshield.alert.dto.FraudAlertEvent"
        session.timeout.ms: 30000
        heartbeat.interval.ms: 10000

  mail:
    host: smtp.gmail.com
    port: 587
    username: your-email@gmail.com
    password: your-app-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  cloud:
    stream:
          kafka:
            binder:
              consumer-properties:
                value.deserializer: org.apache.kafka.common.serialization.StringDeserializer
                key.deserializer: org.apache.kafka.common.serialization.StringDeserializer

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"

kafka:
  topic:
    fraud-alerts: fraud-alerts
