server:
  port: 8080

spring:
  cloud:
#    function:
#      definition: none
    gateway:
      server:
        webmvc:
          routes:
            - id: user-service-auth
              uri: lb://user-service
              predicates:
                - Path=/api/auth/**

            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/api/users/**

            - id: merchant-registration
              uri: lb://user-service
              predicates:
                - Path=/api/merchant/**

            - id: b2b-transactions
              uri: lb://transaction-service
              predicates:
                - Path=/api/v1/transactions/**

            - id: transaction-service
              uri: lb://transaction-service
              predicates:
                - Path=/api/transactions/**

            - id: fraud-service
              uri: lb://fraud-detection-service
              predicates:
                - Path=/api/fraud/**

            - id: alert-service
              uri: lb://alert-service
              predicates:
                - Path=/api/alerts/**

            - id: report-service
              uri: lb://report-service
              predicates:
                - Path=/api/reports/**

  web:
    cors:
      allowed-origin-patterns:
        - "http://localhost:5173"
        - "http://localhost:3000"
        - "http://localhost:*"
      allowed-methods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      allowed-headers: "*"
      allow-credentials: true
      max-age: 3600

security:
  jwt:
    secret: ${JWT_SECRET}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server.requests: true
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans