server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/fraudshielddb?TimeZone=Asia/Kolkata
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: "transactionEvent:com.fraudshield.transaction.kafka.TransactionEvent"

  data:
    redis:
      host: localhost
      port: 6379
  cloud:
    stream:
          kafka:
            binder:
              consumer-properties:
                value.deserializer: org.apache.kafka.common.serialization.StringDeserializer
                key.deserializer: org.apache.kafka.common.serialization.StringDeserializer

kafka:
  topic:
    transaction-events: transaction-events
    fraud-alerts: fraud-alerts
    notification-events: notification-events
    audit-log: audit-log

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
