server:
  port: 8084

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/fraudshielddb?TimeZone=Asia/Kolkata
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"

security:
  jwt:
    secret: ${JWT_SECRET}
    expiration: 86400000