server:
  port: 8084

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fraudshielddb?TimeZone=Asia/Kolkata
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    jwt:
      secret: fraudshield-secret-key-must-be-at-least-256-bits-long
      expiration: 86400000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"